language: cpp
os: osx
compiler: clang
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ./run_unit_tests
notifications:
  email:
    - abramov.ed@phystech.edu
    - evgenabramov239@gmail.com
